class Character:
    def __init__(self, name, anime, gender, rarity, image_path):
        self.name = name
        self.anime = anime
        self.gender = gender
        self.rarity = rarity
        self.image_path = image_path
        self.status = "Disponible"
        self.owner = None

LEGENDARIO = 1
EPICO = 5
RARO = 15
POCO_COMUN = 30
COMUN = 49

characters = [
    # ==================== ONE PIECE (50) ====================
    Character("Monkey D. Luffy", "One Piece", "Masculino", LEGENDARIO, "images/luffy.png"),
    Character("Roronoa Zoro", "One Piece", "Masculino", EPICO, "images/zoro.png"),
    Character("Nami", "One Piece", "Femenino", EPICO, "images/nami.png"),
    Character("Sanji", "One Piece", "Masculino", EPICO, "images/sanji.png"),
    Character("Usopp", "One Piece", "Masculino", EPICO, "images/usopp.png"),
    Character("Tony Tony Chopper", "One Piece", "Masculino", EPICO, "images/chopper.png"),
    Character("Nico Robin", "One Piece", "Femenino", EPICO, "images/robin.png"),
    Character("Franky", "One Piece", "Masculino", EPICO, "images/franky.png"),
    Character("Brook", "One Piece", "Masculino", EPICO, "images/brook.png"),
    Character("Jinbe", "One Piece", "Masculino", EPICO, "images/jinbe.png"),
    Character("Shanks", "One Piece", "Masculino", EPICO, "images/shanks.png"),
    Character("Portgas D. Ace", "One Piece", "Masculino", RARO, "images/ace.png"),
    Character("Trafalgar Law", "One Piece", "Masculino", RARO, "images/law.png"),
    Character("Boa Hancock", "One Piece", "Femenino", RARO, "images/hancock.png"),
    Character("Sabo", "One Piece", "Masculino", RARO, "images/sabo.png"),
    Character("Dracule Mihawk", "One Piece", "Masculino", RARO, "images/mihawk.png"),
    Character("Donquixote Doflamingo", "One Piece", "Masculino", RARO, "images/doflamingo.png"),
    Character("Charlotte Katakuri", "One Piece", "Masculino", RARO, "images/katakuri.png"),
    Character("Big Mom", "One Piece", "Femenino", RARO, "images/bigmom.png"),
    Character("Kaido", "One Piece", "Masculino", RARO, "images/kaido.png"),
    Character("Blackbeard", "One Piece", "Masculino", RARO, "images/blackbeard.png"),
    Character("Enel", "One Piece", "Masculino", POCO_COMUN, "images/enel.png"),
    Character("Crocodile", "One Piece", "Masculino", POCO_COMUN, "images/crocodile.png"),
    Character("Rob Lucci", "One Piece", "Masculino", POCO_COMUN, "images/lucci.png"),
    Character("Kizaru", "One Piece", "Masculino", POCO_COMUN, "images/kizaru.png"),
    Character("Fujitora", "One Piece", "Masculino", POCO_COMUN, "images/fujitora.png"),
    Character("Coby", "One Piece", "Masculino", POCO_COMUN, "images/coby.png"),
    Character("Helmeppo", "One Piece", "Masculino", POCO_COMUN, "images/helmeppo.png"),
    Character("Smoker", "One Piece", "Masculino", POCO_COMUN, "images/smoker.png"),
    Character("Tashigi", "One Piece", "Femenino", POCO_COMUN, "images/tashigi.png"),
    Character("Pedro", "One Piece", "Masculino", POCO_COMUN, "images/pedro.png"),
    Character("Hachi", "One Piece", "Masculino", COMUN, "images/hachi.png"),
    Character("Cabaji", "One Piece", "Masculino", COMUN, "images/cabaji.png"),
    Character("Gin", "One Piece", "Masculino", COMUN, "images/gin.png"),
    Character("Kuroobi", "One Piece", "Masculino", COMUN, "images/kuroobi.png"),
    Character("Alvida", "One Piece", "Femenino", COMUN, "images/alvida.png"),
    Character("T-Bone", "One Piece", "Masculino", COMUN, "images/tbone.png"),
    Character("Hina", "One Piece", "Femenino", COMUN, "images/hina.png"),
    Character("Domino", "One Piece", "Femenino", COMUN, "images/domino.png"),
    Character("Fukaboshi", "One Piece", "Masculino", COMUN, "images/fukaboshi.png"),

    # ==================== NARUTO (50) ====================
    Character("Naruto Uzumaki", "Naruto", "Masculino", LEGENDARIO, "images/naruto.png"),
    Character("Sasuke Uchiha", "Naruto", "Masculino", EPICO, "images/sasuke.png"),
    Character("Sakura Haruno", "Naruto", "Femenino", EPICO, "images/sakura.png"),
    Character("Kakashi Hatake", "Naruto", "Masculino", EPICO, "images/kakashi.png"),
    Character("Gaara", "Naruto", "Masculino", EPICO, "images/gaara.png"),
    Character("Itachi Uchiha", "Naruto", "Masculino", EPICO, "images/itachi.png"),
    Character("Jiraiya", "Naruto", "Masculino", EPICO, "images/jiraiya.png"),
    Character("Orochimaru", "Naruto", "Masculino", EPICO, "images/orochimaru.png"),
    Character("Tsunade", "Naruto", "Femenino", EPICO, "images/tsunade.png"),
    Character("Madara Uchiha", "Naruto", "Masculino", EPICO, "images/madara.png"),
    Character("Shikamaru Nara", "Naruto", "Masculino", RARO, "images/shikamaru.png"),
    Character("Choji Akimichi", "Naruto", "Masculino", RARO, "images/choji.png"),
    Character("Ino Yamanaka", "Naruto", "Femenino", RARO, "images/ino.png"),
    Character("Hinata Hyuga", "Naruto", "Femenino", RARO, "images/hinata.png"),
    Character("Neji Hyuga", "Naruto", "Masculino", RARO, "images/neji.png"),
    Character("Rock Lee", "Naruto", "Masculino", RARO, "images/rocklee.png"),
    Character("Might Guy", "Naruto", "Masculino", RARO, "images/mightguy.png"),
    Character("Kiba Inuzuka", "Naruto", "Masculino", RARO, "images/kiba.png"),
    Character("Akamaru", "Naruto", "Masculino", RARO, "images/akamaru.png"),
    Character("Sai", "Naruto", "Masculino", RARO, "images/sai.png"),
    Character("Temari", "Naruto", "Femenino", POCO_COMUN, "images/temari.png"),
    Character("Kankuro", "Naruto", "Masculino", POCO_COMUN, "images/kankuro.png"),
    Character("Hidan", "Naruto", "Masculino", POCO_COMUN, "images/hidan.png"),
    Character("Kakuzu", "Naruto", "Masculino", POCO_COMUN, "images/kakuzu.png"),
    Character("Deidara", "Naruto", "Masculino", POCO_COMUN, "images/deidara.png"),
    Character("Sasori", "Naruto", "Masculino", POCO_COMUN, "images/sasori.png"),
    Character("Konan", "Naruto", "Femenino", POCO_COMUN, "images/konan.png"),
    Character("Pain/Nagato", "Naruto", "Masculino", POCO_COMUN, "images/pain.png"),
    Character("Killer Bee", "Naruto", "Masculino", POCO_COMUN, "images/killerbee.png"),
    Character("Minato Namikaze", "Naruto", "Masculino", POCO_COMUN, "images/minato.png"),
    Character("Iruka Umino", "Naruto", "Masculino", COMUN, "images/iruka.png"),
    Character("Anko Mitarashi", "Naruto", "Femenino", COMUN, "images/anko.png"),
    Character("Yamato", "Naruto", "Masculino", COMUN, "images/yamato.png"),
    Character("Shino Aburame", "Naruto", "Masculino", COMUN, "images/shino.png"),
    Character("Kurenai Yuhi", "Naruto", "Femenino", COMUN, "images/kurenai.png"),
    Character("Asuma Sarutobi", "Naruto", "Masculino", COMUN, "images/asuma.png"),
    Character("Choza Akimichi", "Naruto", "Masculino", COMUN, "images/choza.png"),
    Character("Hiashi Hyuga", "Naruto", "Masculino", COMUN, "images/hiashi.png"),
    Character("Tenten", "Naruto", "Femenino", COMUN, "images/tenten.png"),
    Character("Shikaku Nara", "Naruto", "Masculino", COMUN, "images/shikaku.png"),

    # ==================== DRAGON BALL (50) ====================
    Character("Son Goku", "Dragon Ball", "Masculino", LEGENDARIO, "images/goku.png"),
    Character("Vegeta", "Dragon Ball", "Masculino", LEGENDARIO, "images/vegeta.png"),
    Character("Son Gohan", "Dragon Ball", "Masculino", EPICO, "images/gohan.png"),
    Character("Piccolo", "Dragon Ball", "Masculino", EPICO, "images/piccolo.png"),
    Character("Trunks", "Dragon Ball", "Masculino", EPICO, "images/trunks.png"),
    Character("Freezer", "Dragon Ball", "Masculino", EPICO, "images/freezer.png"),
    Character("Cell", "Dragon Ball", "Masculino", EPICO, "images/cell.png"),
    Character("Majin Buu", "Dragon Ball", "Masculino", EPICO, "images/buu.png"),
    Character("Krillin", "Dragon Ball", "Masculino", RARO, "images/krillin.png"),
    Character("Yamcha", "Dragon Ball", "Masculino", RARO, "images/yamcha.png"),
    Character("Tien Shinhan", "Dragon Ball", "Masculino", RARO, "images/tien.png"),
    Character("Chiaotzu", "Dragon Ball", "Masculino", RARO, "images/chiaotzu.png"),
    Character("Bulma", "Dragon Ball", "Femenino", RARO, "images/bulma.png"),
    Character("Chi-Chi", "Dragon Ball", "Femenino", RARO, "images/chichi.png"),
    Character("Goten", "Dragon Ball", "Masculino", RARO, "images/goten.png"),
    Character("Android 18", "Dragon Ball", "Femenino", RARO, "images/android18.png"),
    Character("Android 17", "Dragon Ball", "Masculino", RARO, "images/android17.png"),
    Character("Beerus", "Dragon Ball", "Masculino", RARO, "images/beerus.png"),
    Character("Whis", "Dragon Ball", "Masculino", POCO_COMUN, "images/whis.png"),
    Character("Videl", "Dragon Ball", "Femenino", POCO_COMUN, "images/videl.png"),
    Character("Hercule", "Dragon Ball", "Masculino", POCO_COMUN, "images/hercule.png"),
    Character("Pan", "Dragon Ball", "Femenino", POCO_COMUN, "images/pan.png"),
    Character("King Kai", "Dragon Ball", "Masculino", POCO_COMUN, "images/kingkai.png"),
    Character("Dende", "Dragon Ball", "Masculino", POCO_COMUN, "images/dende.png"),
    Character("Supreme Kai", "Dragon Ball", "Masculino", POCO_COMUN, "images/supremekai.png"),
    Character("Goku Black", "Dragon Ball", "Masculino", POCO_COMUN, "images/gokublack.png"),
    Character("Zamasu", "Dragon Ball", "Masculino", POCO_COMUN, "images/zamasu.png"),
    Character("Bardock", "Dragon Ball", "Masculino", POCO_COMUN, "images/bardock.png"),
    Character("Raditz", "Dragon Ball", "Masculino", POCO_COMUN, "images/raditz.png"),
    Character("Nappa", "Dragon Ball", "Masculino", POCO_COMUN, "images/nappa.png"),
    Character("Broly", "Dragon Ball", "Masculino", POCO_COMUN, "images/broly.png"),
    Character("Gogeta", "Dragon Ball", "Masculino", POCO_COMUN, "images/gogeta.png"),
    Character("Vegito", "Dragon Ball", "Masculino", POCO_COMUN, "images/vegito.png"),
    Character("Launch", "Dragon Ball", "Femenino", COMUN, "images/launch.png"),
    Character("Yajirobe", "Dragon Ball", "Masculino", COMUN, "images/yajirobe.png"),
    Character("Puar", "Dragon Ball", "Masculino", COMUN, "images/puar.png"),
    Character("Oolong", "Dragon Ball", "Masculino", COMUN, "images/oolong.png"),
    Character("Kami", "Dragon Ball", "Masculino", COMUN, "images/kami.png"),
    Character("Korin", "Dragon Ball", "Masculino", COMUN, "images/korin.png"),
    Character("Dr. Gero", "Dragon Ball", "Masculino", COMUN, "images/gero.png"),

    # ==================== BAKI (15) ====================
    Character("Baki Hanma", "Baki", "Masculino", LEGENDARIO, "images/baki.png"),
    Character("Yujiro Hanma", "Baki", "Masculino", EPICO, "images/yujiro.png"),
    Character("Doppo Orochi", "Baki", "Masculino", EPICO, "images/doppo.png"),
    Character("Jack Hanma", "Baki", "Masculino", RARO, "images/jack.png"),
    Character("Katsumi Orochi", "Baki", "Masculino", RARO, "images/katsumi.png"),
    Character("Kaioh Retsu", "Baki", "Masculino", POCO_COMUN, "images/retsu.png"),
    Character("Mohammad Alai", "Baki", "Masculino", POCO_COMUN, "images/alai.png"),
    Character("Biscuit Oliva", "Baki", "Masculino", POCO_COMUN, "images/oliva.png"),
    Character("Goki Shibukawa", "Baki", "Masculino", POCO_COMUN, "images/shibukawa.png"),
    Character("Kosho Shinogi", "Baki", "Masculino", COMUN, "images/kosho.png"),
    Character("Hanayama Kaoru", "Baki", "Masculino", COMUN, "images/hanayama.png"),
    Character("Ryozo", "Baki", "Masculino", COMUN, "images/ryozo.png"),
    Character("Kanoh Agito", "Baki", "Masculino", COMUN, "images/kanoh.png"),
    Character("Maki", "Baki", "Femenino", COMUN, "images/maki_baki.png"),

    # ==================== BLACK CLOVER (25) ====================
    Character("Asta", "Black Clover", "Masculino", LEGENDARIO, "images/asta.png"),
    Character("Yuno", "Black Clover", "Masculino", EPICO, "images/yuno.png"),
    Character("Yami Sukehiro", "Black Clover", "Masculino", EPICO, "images/yami.png"),
    Character("Noelle Silva", "Black Clover", "Femenino", EPICO, "images/noelle.png"),
    Character("Julius Novachrono", "Black Clover", "Masculino", EPICO, "images/julius.png"),
    Character("William Vangeance", "Black Clover", "Masculino", EPICO, "images/william.png"),
    Character("Luck Voltia", "Black Clover", "Masculino", RARO, "images/luck.png"),
    Character("Magna Swing", "Black Clover", "Masculino", RARO, "images/magna.png"),
    Character("Vanessa Enoteca", "Black Clover", "Femenino", RARO, "images/vanessa.png"),
    Character("Charlotte Roselei", "Black Clover", "Femenino", RARO, "images/charlotte.png"),
    Character("Fuegoleon Vermillion", "Black Clover", "Masculino", RARO, "images/fuegoleon.png"),
    Character("Gordon Agrippa", "Black Clover", "Masculino", POCO_COMUN, "images/gordon.png"),
    Character("Grey", "Black Clover", "Femenino", POCO_COMUN, "images/grey.png"),
    Character("Zora Ideale", "Black Clover", "Masculino", POCO_COMUN, "images/zora.png"),
    Character("Henry Legolant", "Black Clover", "Masculino", POCO_COMUN, "images/henry.png"),
    Character("Klaus Lunettes", "Black Clover", "Masculino", POCO_COMUN, "images/klaus.png"),
    Character("Rill Boismortier", "Black Clover", "Masculino", POCO_COMUN, "images/rill.png"),
    Character("Dorothy Unsworth", "Black Clover", "Femenino", POCO_COMUN, "images/dorothy.png"),
    Character("Langris Vaude", "Black Clover", "Masculino", POCO_COMUN, "images/langris.png"),
    Character("Finral Roulacase", "Black Clover", "Masculino", COMUN, "images/finral.png"),
    Character("Leopold Vermillion", "Black Clover", "Masculino", COMUN, "images/leopold.png"),
    Character("Mereoleona Vermillion", "Black Clover", "Femenino", COMUN, "images/mereoleona.png"),
    Character("Mimosa Vermillion", "Black Clover", "Femenino", COMUN, "images/mimosa.png"),

    # ==================== BLUE LOCK (15) ====================
    Character("Yoichi Isagi", "Blue Lock", "Masculino", LEGENDARIO, "images/isagi.png"),
    Character("Rensuke Kunigami", "Blue Lock", "Masculino", EPICO, "images/kunigami.png"),
    Character("Meguru Bachira", "Blue Lock", "Masculino", EPICO, "images/bachira.png"),
    Character("Seishiro Nagi", "Blue Lock", "Masculino", RARO, "images/nagi.png"),
    Character("Hyoma Chigiri", "Blue Lock", "Masculino", RARO, "images/chigiri.png"),
    Character("Rin Itoshi", "Blue Lock", "Masculino", RARO, "images/rin.png"),
    Character("Anri Tezuka", "Blue Lock", "Femenino", POCO_COMUN, "images/anri.png"),
    Character("Gin Gagamaru", "Blue Lock", "Masculino", POCO_COMUN, "images/gagamaru.png"),
    Character("Reo Mikage", "Blue Lock", "Masculino", POCO_COMUN, "images/reo.png"),
    Character("Wataru Kuon", "Blue Lock", "Masculino", POCO_COMUN, "images/kuon.png"),
    Character("Ryohei Shidou", "Blue Lock", "Masculino", COMUN, "images/shidou.png"),

    # ==================== MY HERO ACADEMIA (15) ====================
    Character("Izuku Midoriya", "My Hero Academia", "Masculino", LEGENDARIO, "images/deku.png"),
    Character("Katsuki Bakugo", "My Hero Academia", "Masculino", EPICO, "images/bakugo.png"),
    Character("Shoto Todoroki", "My Hero Academia", "Masculino", EPICO, "images/todoroki.png"),
    Character("Ochaco Uraraka", "My Hero Academia", "Femenino", RARO, "images/uraraka.png"),
    Character("Tenya Iida", "My Hero Academia", "Masculino", RARO, "images/iida.png"),
    Character("Momo Yaoyorozu", "My Hero Academia", "Femenino", RARO, "images/momo.png"),
    Character("Eijiro Kirishima", "My Hero Academia", "Masculino", POCO_COMUN, "images/kirishima.png"),
    Character("Fumikage Tokoyami", "My Hero Academia", "Masculino", POCO_COMUN, "images/tokoyami.png"),
    Character("Tsuyu Asui", "My Hero Academia", "Femenino", POCO_COMUN, "images/asui.png"),
    Character("Minoru Mineta", "My Hero Academia", "Masculino", POCO_COMUN, "images/mineta.png"),
    Character("Denki Kaminari", "My Hero Academia", "Masculino", POCO_COMUN, "images/kaminari.png"),
    Character("Yuga Aoyama", "My Hero Academia", "Masculino", COMUN, "images/aoyama.png"),
    Character("Mashirao Ojiro", "My Hero Academia", "Masculino", COMUN, "images/ojiro.png"),
    Character("Koji Koda", "My Hero Academia", "Masculino", COMUN, "images/koda.png"),
    Character("Rikido Sato", "My Hero Academia", "Masculino", COMUN, "images/sato.png"),

    # ==================== DEATH NOTE (15) ====================
    Character("L", "Death Note", "Masculino", LEGENDARIO, "images/l.png"),
    Character("Light Yagami", "Death Note", "Masculino", LEGENDARIO, "images/light.png"),
    Character("Ryuk", "Death Note", "Masculino", EPICO, "images/ryuk.png"),
    Character("Near", "Death Note", "Masculino", EPICO, "images/near.png"),
    Character("Mello", "Death Note", "Masculino", EPICO, "images/mello.png"),
    Character("Soichiro Yagami", "Death Note", "Masculino", RARO, "images/soichiro.png"),
    Character("Touta Matsuda", "Death Note", "Masculino", RARO, "images/matsuda.png"),
    Character("Sayu Yagami", "Death Note", "Femenino", RARO, "images/sayu.png"),
    Character("Rem", "Death Note", "Femenino", POCO_COMUN, "images/rem.png"),
    Character("Watari", "Death Note", "Masculino", POCO_COMUN, "images/watari.png"),
    Character("Kiyomi Takada", "Death Note", "Femenino", POCO_COMUN, "images/takada.png"),
    Character("Teru Mikami", "Death Note", "Masculino", POCO_COMUN, "images/mikami.png"),
    Character("Kanzo Mogi", "Death Note", "Masculino", POCO_COMUN, "images/mogi.png"),
    Character("Shuichi Aizawa", "Death Note", "Masculino", COMUN, "images/aizawa_dn.png"),
    Character("Raye Penber", "Death Note", "Masculino", COMUN, "images/raye.png"),
    Character("Naomi Misora", "Death Note", "Femenino", COMUN, "images/naomi.png"),

    # ==================== BLEACH (50) ====================
    Character("Ichigo Kurosaki", "Bleach", "Masculino", LEGENDARIO, "images/ichigo.png"),
    Character("Rukia Kuchiki", "Bleach", "Femenino", LEGENDARIO, "images/rukia.png"),
    Character("Byakuya Kuchiki", "Bleach", "Masculino", EPICO, "images/byakuya.png"),
    Character("Renji Abarai", "Bleach", "Masculino", EPICO, "images/renji.png"),
    Character("Toshiro Hitsugaya", "Bleach", "Masculino", EPICO, "images/hitsugaya.png"),
    Character("Kenpachi Zaraki", "Bleach", "Masculino", EPICO, "images/kenpachi.png"),
    Character("Sosuke Aizen", "Bleach", "Masculino", EPICO, "images/aizen.png"),
    Character("Gin Ichimaru", "Bleach", "Masculino", EPICO, "images/gin.png"),
    Character("Ulquiorra Cifer", "Bleach", "Masculino", EPICO, "images/ulquiorra.png"),
    Character("Orihime Inoue", "Bleach", "Femenino", RARO, "images/orihime.png"),
    Character("Uryu Ishida", "Bleach", "Masculino", RARO, "images/uryu.png"),
    Character("Yasutora Chad Sado", "Bleach", "Masculino", RARO, "images/chad.png"),
    Character("Rangiku Matsumoto", "Bleach", "Femenino", RARO, "images/rangiku.png"),
    Character("Shunsui Kyoraku", "Bleach", "Masculino", RARO, "images/shunsui.png"),
    Character("Nnoitra Gilga", "Bleach", "Masculino", RARO, "images/nnoitra.png"),
    Character("Grimmjow Jaegerjaquez", "Bleach", "Masculino", RARO, "images/grimmjow.png"),
    Character("Nemu Kurotsuchi", "Bleach", "Femenino", RARO, "images/nemu.png"),
    Character("Mayuri Kurotsuchi", "Bleach", "Masculino", RARO, "images/mayuri.png"),
    Character("Kukaku Shiba", "Bleach", "Femenino", POCO_COMUN, "images/kukaku.png"),
    Character("Ganju Shiba", "Bleach", "Masculino", POCO_COMUN, "images/ganju.png"),
    Character("Jushiro Ukitake", "Bleach", "Masculino", POCO_COMUN, "images/ukitake.png"),
    Character("Shuhei Hisagi", "Bleach", "Masculino", POCO_COMUN, "images/hisagi.png"),
    Character("Kaname Tosen", "Bleach", "Masculino", POCO_COMUN, "images/tosen.png"),
    Character("Tier Harribel", "Bleach", "Femenino", POCO_COMUN, "images/harribel.png"),
    Character("Ikkaku Madarame", "Bleach", "Masculino", COMUN, "images/ikkaku.png"),
    Character("Yumichika Ayasegawa", "Bleach", "Masculino", COMUN, "images/yumichika.png"),
    Character("Izuru Kira", "Bleach", "Masculino", COMUN, "images/kira.png"),

    # ==================== JUJUTSU KAISEN (25) ====================
    Character("Yuji Itadori", "Jujutsu Kaisen", "Masculino", LEGENDARIO, "images/yuji.png"),
    Character("Satoru Gojo", "Jujutsu Kaisen", "Masculino", LEGENDARIO, "images/gojo.png"),
    Character("Megumi Fushiguro", "Jujutsu Kaisen", "Masculino", EPICO, "images/megumi.png"),
    Character("Nobara Kugisaki", "Jujutsu Kaisen", "Femenino", EPICO, "images/nobara.png"),
    Character("Suguru Geto", "Jujutsu Kaisen", "Masculino", EPICO, "images/geto.png"),
    Character("Sukuna", "Jujutsu Kaisen", "Masculino", EPICO, "images/sukuna.png"),
    Character("Kento Nanami", "Jujutsu Kaisen", "Masculino", EPICO, "images/nanami.png"),
    Character("Panda", "Jujutsu Kaisen", "Masculino", RARO, "images/panda.png"),
    Character("Toge Inumaki", "Jujutsu Kaisen", "Masculino", RARO, "images/inumaki.png"),
    Character("Maki Zenin", "Jujutsu Kaisen", "Femenino", RARO, "images/maki.png"),
    Character("Aoi Todo", "Jujutsu Kaisen", "Masculino", RARO, "images/todo.png"),
    Character("Mai Zenin", "Jujutsu Kaisen", "Femenino", RARO, "images/mai.png"),
    Character("Junpei Yoshino", "Jujutsu Kaisen", "Masculino", RARO, "images/junpei.png"),
    Character("Choso", "Jujutsu Kaisen", "Masculino", RARO, "images/choso.png"),
    Character("Kasumi Miwa", "Jujutsu Kaisen", "Femenino", POCO_COMUN, "images/miwa.png"),
    Character("Mechamaru", "Jujutsu Kaisen", "Masculino", POCO_COMUN, "images/mechamaru.png"),
    Character("Hanami", "Jujutsu Kaisen", "Masculino", POCO_COMUN, "images/hanami.png"),
    Character("Jogo", "Jujutsu Kaisen", "Masculino", POCO_COMUN, "images/jogo.png"),
    Character("Naoya Zenin", "Jujutsu Kaisen", "Masculino", COMUN, "images/naoya.png"),
    Character("Toji Fushiguro", "Jujutsu Kaisen", "Masculino", COMUN, "images/toji.png"),

    # ==================== KIMETSU NO YAIBA (25) ====================
    Character("Tanjiro Kamado", "Kimetsu no Yaiba", "Masculino", LEGENDARIO, "images/tanjiro.png"),
    Character("Nezuko Kamado", "Kimetsu no Yaiba", "Femenino", LEGENDARIO, "images/nezuko.png"),
    Character("Giyu Tomioka", "Kimetsu no Yaiba", "Masculino", EPICO, "images/giyu.png"),
    Character("Kyojuro Rengoku", "Kimetsu no Yaiba", "Masculino", EPICO, "images/rengoku.png"),
    Character("Shinobu Kocho", "Kimetsu no Yaiba", "Femenino", EPICO, "images/shinobu.png"),
    Character("Inosuke Hashibira", "Kimetsu no Yaiba", "Masculino", EPICO, "images/inosuke.png"),
    Character("Zenitsu Agatsuma", "Kimetsu no Yaiba", "Masculino", EPICO, "images/zenitsu.png"),
    Character("Muzan Kibutsuji", "Kimetsu no Yaiba", "Masculino", EPICO, "images/muzan.png"),
    Character("Sanemi Shinazugawa", "Kimetsu no Yaiba", "Masculino", RARO, "images/sanemi.png"),
    Character("Genya Shinazugawa", "Kimetsu no Yaiba", "Masculino", RARO, "images/genya.png"),
    Character("Muichiro Tokito", "Kimetsu no Yaiba", "Masculino", RARO, "images/muichiro.png"),
    Character("Mitsuri Kanroji", "Kimetsu no Yaiba", "Femenino", RARO, "images/mitsuri.png"),
    Character("Obanai Iguro", "Kimetsu no Yaiba", "Masculino", RARO, "images/obanai.png"),
    Character("Gyomei Himejima", "Kimetsu no Yaiba", "Masculino", RARO, "images/gyomei.png"),
    Character("Tengen Uzui", "Kimetsu no Yaiba", "Masculino", RARO, "images/tengen.png"),
    Character("Kanao Tsuyuri", "Kimetsu no Yaiba", "Femenino", POCO_COMUN, "images/kanao.png"),
    Character("Sabito", "Kimetsu no Yaiba", "Masculino", POCO_COMUN, "images/sabito.png"),
    Character("Tamayo", "Kimetsu no Yaiba", "Femenino", POCO_COMUN, "images/tamayo.png"),
    Character("Rui", "Kimetsu no Yaiba", "Masculino", POCO_COMUN, "images/rui.png"),
    Character("Akaza", "Kimetsu no Yaiba", "Masculino", POCO_COMUN, "images/akaza.png"),
    Character("Doma", "Kimetsu no Yaiba", "Masculino", COMUN, "images/doma.png"),
    Character("Kokushibo", "Kimetsu no Yaiba", "Masculino", COMUN, "images/kokushibo.png"),
    Character("Enmu", "Kimetsu no Yaiba", "Masculino", COMUN, "images/enmu.png"),

    # ==================== SHINGEKI NO KYOJIN (30) ====================
    Character("Eren Yeager", "Shingeki no Kyojin", "Masculino", LEGENDARIO, "images/eren.png"),
    Character("Mikasa Ackerman", "Shingeki no Kyojin", "Femenino", LEGENDARIO, "images/mikasa.png"),
    Character("Armin Arlert", "Shingeki no Kyojin", "Masculino", EPICO, "images/armin.png"),
    Character("Levi Ackerman", "Shingeki no Kyojin", "Masculino", EPICO, "images/levi.png"),
    Character("Historia Reiss", "Shingeki no Kyojin", "Femenino", EPICO, "images/historia.png"),
    Character("Jean Kirstein", "Shingeki no Kyojin", "Masculino", EPICO, "images/jean.png"),
    Character("Sasha Blouse", "Shingeki no Kyojin", "Femenino", EPICO, "images/sasha.png"),
    Character("Connie Springer", "Shingeki no Kyojin", "Masculino", EPICO, "images/connie.png"),
    Character("Reiner Braun", "Shingeki no Kyojin", "Masculino", RARO, "images/reiner.png"),
    Character("Bertholdt Hoover", "Shingeki no Kyojin", "Masculino", RARO, "images/bertholdt.png"),
    Character("Hange Zoe", "Shingeki no Kyojin", "Femenino", RARO, "images/hange.png"),
    Character("Erwin Smith", "Shingeki no Kyojin", "Masculino", RARO, "images/erwin.png"),
    Character("Annie Leonhart", "Shingeki no Kyojin", "Femenino", RARO, "images/annie.png"),
    Character("Ymir", "Shingeki no Kyojin", "Femenino", POCO_COMUN, "images/ymir.png"),
    Character("Marco Bott", "Shingeki no Kyojin", "Masculino", POCO_COMUN, "images/marco.png"),
    Character("Pieck Finger", "Shingeki no Kyojin", "Femenino", POCO_COMUN, "images/pieck.png"),
    Character("Falco Grice", "Shingeki no Kyojin", "Masculino", POCO_COMUN, "images/falco.png"),
    Character("Gabi Braun", "Shingeki no Kyojin", "Femenino", POCO_COMUN, "images/gabi.png"),
    Character("Petra Ral", "Shingeki no Kyojin", "Femenino", POCO_COMUN, "images/petra.png"),
    Character("Gunther Schultz", "Shingeki no Kyojin", "Masculino", COMUN, "images/gunther.png"),
    Character("Oluo Bozado", "Shingeki no Kyojin", "Masculino", COMUN, "images/oluo.png"),
    Character("Hitch Dreyse", "Shingeki no Kyojin", "Femenino", COMUN, "images/hitch.png"),

    # ==================== SPY X FAMILY (15) ====================
    Character("Loid Forger", "Spy x Family", "Masculino", LEGENDARIO, "images/loid.png"),
    Character("Yor Forger", "Spy x Family", "Femenino", EPICO, "images/yor.png"),
    Character("Anya Forger", "Spy x Family", "Femenino", EPICO, "images/anya.png"),
    Character("Franky Franklin", "Spy x Family", "Masculino", EPICO, "images/franky_spy.png"),
    Character("Damian Desmond", "Spy x Family", "Masculino", RARO, "images/damian.png"),
    Character("Becky Blackbell", "Spy x Family", "Femenino", RARO, "images/becky.png"),
    Character("Henry Henderson", "Spy x Family", "Masculino", RARO, "images/henderson.png"),
    Character("Fiona Frost", "Spy x Family", "Femenino", POCO_COMUN, "images/fiona.png"),
    Character("Yuri Briar", "Spy x Family", "Masculino", POCO_COMUN, "images/yuri.png"),
    Character("Sylvia Sherwood", "Spy x Family", "Femenino", POCO_COMUN, "images/sylvia.png"),
    Character("Bond Forger", "Spy x Family", "Masculino", POCO_COMUN, "images/bond.png"),
    Character("Donovan Desmond", "Spy x Family", "Masculino", COMUN, "images/donovan.png"),

    # ==================== ONE PUNCH MAN (25) ====================
    Character("Saitama", "One Punch Man", "Masculino", LEGENDARIO, "images/saitama.png"),
    Character("Genos", "One Punch Man", "Masculino", EPICO, "images/genos.png"),
    Character("Bang", "One Punch Man", "Masculino", EPICO, "images/bang.png"),
    Character("Tatsumaki", "One Punch Man", "Femenino", EPICO, "images/tatsumaki.png"),
    Character("Fubuki", "One Punch Man", "Femenino", EPICO, "images/fubuki.png"),
    Character("Garou", "One Punch Man", "Masculino", EPICO, "images/garou.png"),
    Character("King", "One Punch Man", "Masculino", EPICO, "images/king.png"),
    Character("Sonic", "One Punch Man", "Masculino", RARO, "images/sonic.png"),
    Character("Puri-Puri Prisoner", "One Punch Man", "Masculino", RARO, "images/puri.png"),
    Character("Metal Knight", "One Punch Man", "Masculino", RARO, "images/metalknight.png"),
    Character("Zombieman", "One Punch Man", "Masculino", RARO, "images/zombieman.png"),
    Character("Atomic Samurai", "One Punch Man", "Masculino", POCO_COMUN, "images/atomic.png"),
    Character("Sweet Mask", "One Punch Man", "Masculino", POCO_COMUN, "images/sweetmask.png"),
    Character("Mumen Rider", "One Punch Man", "Masculino", COMUN, "images/mumen.png"),

    # ==================== FULLMETAL ALCHEMIST (25) ====================
    Character("Edward Elric", "Fullmetal Alchemist", "Masculino", LEGENDARIO, "images/edward.png"),
    Character("Alphonse Elric", "Fullmetal Alchemist", "Masculino", LEGENDARIO, "images/alphonse.png"),
    Character("Roy Mustang", "Fullmetal Alchemist", "Masculino", EPICO, "images/mustang.png"),
    Character("Riza Hawkeye", "Fullmetal Alchemist", "Femenino", EPICO, "images/riza.png"),
    Character("Scar", "Fullmetal Alchemist", "Masculino", EPICO, "images/scar.png"),
    Character("King Bradley", "Fullmetal Alchemist", "Masculino", EPICO, "images/bradley.png"),
    Character("Ling Yao", "Fullmetal Alchemist", "Masculino", EPICO, "images/ling.png"),
    Character("Winry Rockbell", "Fullmetal Alchemist", "Femenino", RARO, "images/winry.png"),
    Character("Olivier Armstrong", "Fullmetal Alchemist", "Femenino", RARO, "images/olivier.png"),
    Character("Alex Armstrong", "Fullmetal Alchemist", "Masculino", RARO, "images/alex.png"),
    Character("Hughes", "Fullmetal Alchemist", "Masculino", RARO, "images/hughes.png"),
    Character("Izumi Curtis", "Fullmetal Alchemist", "Femenino", POCO_COMUN, "images/izumi.png"),
    Character("Gluttony", "Fullmetal Alchemist", "Masculino", POCO_COMUN, "images/gluttony.png"),
    Character("Envy", "Fullmetal Alchemist", "Masculino", POCO_COMUN, "images/envy.png"),
    Character("Nina Tucker", "Fullmetal Alchemist", "Femenino", COMUN, "images/nina.png"),

    # ==================== HUNTER X HUNTER (15) ====================
    Character("Gon Freecss", "Hunter x Hunter", "Masculino", LEGENDARIO, "images/gon.png"),
    Character("Killua Zoldyck", "Hunter x Hunter", "Masculino", EPICO, "images/killua.png"),
    Character("Kurapika", "Hunter x Hunter", "Masculino", EPICO, "images/kurapika.png"),
    Character("Leorio Paradinight", "Hunter x Hunter", "Masculino", EPICO, "images/leorio.png"),
    Character("Hisoka", "Hunter x Hunter", "Masculino", EPICO, "images/hisoka.png"),
    Character("Chrollo Lucilfer", "Hunter x Hunter", "Masculino", RARO, "images/chrollo.png"),
    Character("Illumi Zoldyck", "Hunter x Hunter", "Masculino", RARO, "images/illumi.png"),
    Character("Feitan", "Hunter x Hunter", "Masculino", RARO, "images/feitan.png"),
    Character("Machi", "Hunter x Hunter", "Femenino", RARO, "images/machi.png"),
    Character("Shalnark", "Hunter x Hunter", "Masculino", POCO_COMUN, "images/shalnark.png"),
    Character("Pakunoda", "Hunter x Hunter", "Femenino", POCO_COMUN, "images/pakunoda.png"),
    Character("Nobunaga", "Hunter x Hunter", "Masculino", POCO_COMUN, "images/nobunaga.png"),
    Character("Franklin", "Hunter x Hunter", "Masculino", COMUN, "images/franklin.png"),
    Character("Phinks", "Hunter x Hunter", "Masculino", COMUN, "images/phinks.png"),

    # ==================== SOLO LEVELING (15) ====================
    Character("Sung Jin-Woo", "Solo Leveling", "Masculino", LEGENDARIO, "images/jinwoo.png"),
    Character("Cha Hae-In", "Solo Leveling", "Femenino", EPICO, "images/chahaein.png"),
    Character("Go Gun-Hee", "Solo Leveling", "Masculino", EPICO, "images/gunhee.png"),
    Character("Thomas Andre", "Solo Leveling", "Masculino", EPICO, "images/thomas.png"),
    Character("Igris", "Solo Leveling", "Masculino", EPICO, "images/igris.png"),
    Character("Beru", "Solo Leveling", "Masculino", RARO, "images/beru.png"),
    Character("Tusk", "Solo Leveling", "Masculino", RARO, "images/tusk.png"),
    Character("Iron", "Solo Leveling", "Masculino", RARO, "images/iron.png"),
    Character("Yoo Jin-Ho", "Solo Leveling", "Masculino", POCO_COMUN, "images/jinho.png"),
    Character("Antares", "Solo Leveling", "Masculino", POCO_COMUN, "images/antares.png"),

    # ==================== FRIEREN (15) ====================
    Character("Frieren", "Frieren", "Femenino", LEGENDARIO, "images/frieren.png"),
    Character("Himmel", "Frieren", "Masculino", EPICO, "images/himmel.png"),
    Character("Eisen", "Frieren", "Masculino", EPICO, "images/eisen.png"),
    Character("Fern", "Frieren", "Femenino", EPICO, "images/fern.png"),
    Character("Stark", "Frieren", "Masculino", RARO, "images/stark.png"),
    Character("Heiter", "Frieren", "Masculino", RARO, "images/heiter.png"),

    # ==================== RE:ZERO (15) ====================
    Character("Subaru Natsuki", "Re:Zero", "Masculino", LEGENDARIO, "images/subaru.png"),
    Character("Emilia", "Re:Zero", "Femenino", EPICO, "images/emilia.png"),
    Character("Rem", "Re:Zero", "Femenino", EPICO, "images/rem_rezero.png"),
    Character("Ram", "Re:Zero", "Femenino", EPICO, "images/ram.png"),
    Character("Roswaal L. Mathers", "Re:Zero", "Masculino", EPICO, "images/roswaal.png"),
    Character("Beatrice", "Re:Zero", "Femenino", RARO, "images/beatrice.png"),
    Character("Crusch Karsten", "Re:Zero", "Femenino", RARO, "images/crusch.png"),
    Character("Felix Argyle", "Re:Zero", "Masculino", RARO, "images/felix.png"),
    Character("Reinhard van Astrea", "Re:Zero", "Masculino", POCO_COMUN, "images/reinhard.png"),
    Character("Echidna", "Re:Zero", "Femenino", POCO_COMUN, "images/echidna.png"),
    Character("Otto Suwen", "Re:Zero", "Masculino", COMUN, "images/otto.png"),
    Character("Garfiel Tinsel", "Re:Zero", "Masculino", COMUN, "images/garfiel.png"),

    # ==================== TOKYO REVENGERS (15) ====================
    Character("Takemichi Hanagaki", "Tokyo Revengers", "Masculino", LEGENDARIO, "images/takemichi.png"),
    Character("Manjiro Mikey Sano", "Tokyo Revengers", "Masculino", EPICO, "images/mikey.png"),
    Character("Ken Draken Ryuguji", "Tokyo Revengers", "Masculino", EPICO, "images/draken.png"),
    Character("Tetta Kisaki", "Tokyo Revengers", "Masculino", EPICO, "images/kisaki.png"),
    Character("Emma Sano", "Tokyo Revengers", "Femenino", EPICO, "images/emma.png"),
    Character("Takashi Mitsuya", "Tokyo Revengers", "Masculino", RARO, "images/mitsuya.png"),
    Character("Chifuyu Matsuno", "Tokyo Revengers", "Masculino", RARO, "images/chifuyu.png"),
    Character("Kazutora Hanemiya", "Tokyo Revengers", "Masculino", RARO, "images/kazutora.png"),
    Character("Hakkai Shiba", "Tokyo Revengers", "Masculino", POCO_COMUN, "images/hakkai.png"),
    Character("Shuji Hanma", "Tokyo Revengers", "Masculino", POCO_COMUN, "images/hanma.png"),

    # ==================== VINLAND SAGA (15) ====================
    Character("Thorfinn", "Vinland Saga", "Masculino", LEGENDARIO, "images/thorfinn.png"),
    Character("Askeladd", "Vinland Saga", "Masculino", EPICO, "images/askeladd.png"),
    Character("Canute", "Vinland Saga", "Masculino", EPICO, "images/canute.png"),
    Character("Thorkell", "Vinland Saga", "Masculino", EPICO, "images/thorkell.png"),
    Character("Bjorn", "Vinland Saga", "Masculino", EPICO, "images/bjorn.png"),
    Character("Floki", "Vinland Saga", "Masculino", RARO, "images/floki.png"),
    Character("Thors", "Vinland Saga", "Masculino", RARO, "images/thors.png"),
    Character("Ketil", "Vinland Saga", "Masculino", RARO, "images/ketil.png"),
    Character("Einar", "Vinland Saga", "Masculino", POCO_COMUN, "images/einar.png"),
    Character("Ylva", "Vinland Saga", "Femenino", POCO_COMUN, "images/ylva.png"),
    Character("Leif", "Vinland Saga", "Masculino", COMUN, "images/leif.png"),

    # ==================== MOB PSYCHO 100 (15) ====================
    Character("Shigeo Mob Kageyama", "Mob Psycho 100", "Masculino", LEGENDARIO, "images/mob.png"),
    Character("Arataka Reigen", "Mob Psycho 100", "Masculino", EPICO, "images/reigen.png"),
    Character("Ritsu Kageyama", "Mob Psycho 100", "Masculino", EPICO, "images/ritsu.png"),
    Character("Teruki Hanazawa", "Mob Psycho 100", "Masculino", EPICO, "images/teruki.png"),
    Character("Dimple", "Mob Psycho 100", "Masculino", RARO, "images/dimple.png"),
    Character("Sho Suzuki", "Mob Psycho 100", "Masculino", RARO, "images/sho.png"),
    Character("Katsuya Serizawa", "Mob Psycho 100", "Masculino", POCO_COMUN, "images/serizawa.png"),
    Character("Tome Kurata", "Mob Psycho 100", "Femenino", POCO_COMUN, "images/tome.png"),

    # ==================== NANATSU NO TAIZAI (25) ====================
    Character("Meliodas", "Nanatsu no Taizai", "Masculino", LEGENDARIO, "images/meliodas.png"),
    Character("Elizabeth Liones", "Nanatsu no Taizai", "Femenino", EPICO, "images/elizabeth.png"),
    Character("Ban", "Nanatsu no Taizai", "Masculino", EPICO, "images/ban.png"),
    Character("Diane", "Nanatsu no Taizai", "Femenino", EPICO, "images/diane.png"),
    Character("King", "Nanatsu no Taizai", "Masculino", EPICO, "images/king_nnt.png"),
    Character("Gowther", "Nanatsu no Taizai", "Masculino", EPICO, "images/gowther.png"),
    Character("Merlin", "Nanatsu no Taizai", "Femenino", EPICO, "images/merlin.png"),
    Character("Escanor", "Nanatsu no Taizai", "Masculino", RARO, "images/escanor.png"),
    Character("Hawk", "Nanatsu no Taizai", "Masculino", RARO, "images/hawk.png"),
    Character("Gilthunder", "Nanatsu no Taizai", "Masculino", RARO, "images/gilthunder.png"),
    Character("Hendrickson", "Nanatsu no Taizai", "Masculino", RARO, "images/hendrickson.png"),
    Character("Jericho", "Nanatsu no Taizai", "Femenino", POCO_COMUN, "images/jericho.png"),
    Character("Ellaine", "Nanatsu no Taizai", "Femenino", POCO_COMUN, "images/ellaine.png"),

    # ==================== POKEMON (15) ====================
    Character("Ash Ketchum", "Pokemon", "Masculino", LEGENDARIO, "images/ash.png"),
    Character("Pikachu", "Pokemon", "Masculino", EPICO, "images/pikachu.png"),
    Character("Misty", "Pokemon", "Femenino", EPICO, "images/misty.png"),
    Character("Brock", "Pokemon", "Masculino", EPICO, "images/brock.png"),
    Character("Gary Oak", "Pokemon", "Masculino", EPICO, "images/gary.png"),
    Character("Jessie", "Pokemon", "Femenino", RARO, "images/jessie.png"),
    Character("James", "Pokemon", "Masculino", RARO, "images/james.png"),
    Character("Meowth", "Pokemon", "Masculino", RARO, "images/meowth.png"),
    Character("May", "Pokemon", "Femenino", POCO_COMUN, "images/may.png"),
    Character("Dawn", "Pokemon", "Femenino", POCO_COMUN, "images/dawn.png"),
    Character("Serena", "Pokemon", "Femenino", POCO_COMUN, "images/serena.png"),
    Character("Iris", "Pokemon", "Femenino", COMUN, "images/iris.png"),
    Character("Cilan", "Pokemon", "Masculino", COMUN, "images/cilan.png"),
    
    # Pokemon Legendarios
    Character("Mewtwo", "Pokemon", "Masculino", LEGENDARIO, "images/mewtwo.png"),
    Character("Mew", "Pokemon", "Masculino", LEGENDARIO, "images/mew.png"),
    Character("Lugia", "Pokemon", "Masculino", LEGENDARIO, "images/lugia.png"),
    Character("Ho-Oh", "Pokemon", "Masculino", LEGENDARIO, "images/hooh.png"),
    Character("Rayquaza", "Pokemon", "Masculino", LEGENDARIO, "images/rayquaza.png"),
    Character("Charizard", "Pokemon", "Masculino", EPICO, "images/charizard.png"),
    Character("Blastoise", "Pokemon", "Masculino", EPICO, "images/blastoise.png"),
    Character("Venusaur", "Pokemon", "Masculino", EPICO, "images/venusaur.png"),
    Character("Gyarados", "Pokemon", "Masculino", EPICO, "images/gyarados.png"),
    Character("Lucario", "Pokemon", "Masculino", EPICO, "images/lucario.png"),
    Character("Greninja", "Pokemon", "Masculino", EPICO, "images/greninja.png"),

    # ==================== HAIKYUU (15) ====================
    Character("Shoyo Hinata", "Haikyuu", "Masculino", LEGENDARIO, "images/hinata.png"),
    Character("Tobio Kageyama", "Haikyuu", "Masculino", EPICO, "images/kageyama.png"),
    Character("Daichi Sawamura", "Haikyuu", "Masculino", EPICO, "images/daichi.png"),
    Character("Koshi Sugawara", "Haikyuu", "Masculino", EPICO, "images/sugawara.png"),
    Character("Asahi Azumane", "Haikyuu", "Masculino", RARO, "images/asahi.png"),
    Character("Yu Nishinoya", "Haikyuu", "Masculino", RARO, "images/nishinoya.png"),
    Character("Ryunosuke Tanaka", "Haikyuu", "Masculino", RARO, "images/tanaka.png"),
    Character("Kei Tsukishima", "Haikyuu", "Masculino", POCO_COMUN, "images/tsukishima.png"),
    Character("Tetsuro Kuroo", "Haikyuu", "Masculino", POCO_COMUN, "images/kuroo.png"),
    Character("Kenma Kozume", "Haikyuu", "Masculino", COMUN, "images/kenma.png"),
    Character("Bokuto Koutarou", "Haikyuu", "Masculino", COMUN, "images/bokuto.png"),

    # ==================== DETECTIVE CONAN (15) ====================
    Character("Conan Edogawa", "Detective Conan", "Masculino", LEGENDARIO, "images/conan.png"),
    Character("Ran Mouri", "Detective Conan", "Femenino", EPICO, "images/ran.png"),
    Character("Kogoro Mouri", "Detective Conan", "Masculino", EPICO, "images/kogoro.png"),
    Character("Ai Haibara", "Detective Conan", "Femenino", EPICO, "images/haibara.png"),
    Character("Heiji Hattori", "Detective Conan", "Masculino", EPICO, "images/heiji.png"),
    Character("Kazuha Toyama", "Detective Conan", "Femenino", RARO, "images/kazuha.png"),
    Character("Sonoko Suzuki", "Detective Conan", "Femenino", RARO, "images/sonoko.png"),
    Character("Shuichi Akai", "Detective Conan", "Masculino", RARO, "images/akai.png"),
    Character("Vermouth", "Detective Conan", "Femenino", POCO_COMUN, "images/vermouth.png"),
    Character("Kaitou Kid", "Detective Conan", "Masculino", COMUN, "images/kid.png"),
    Character("Hiroshi Agasa", "Detective Conan", "Masculino", COMUN, "images/agasa.png"),

    # ==================== MUSHOKU TENSEI (15) ====================
    Character("Rudeus Greyrat", "Mushoku Tensei", "Masculino", LEGENDARIO, "images/rudeus.png"),
    Character("Roxy Migurdia", "Mushoku Tensei", "Femenino", EPICO, "images/roxy.png"),
    Character("Sylphy", "Mushoku Tensei", "Femenino", EPICO, "images/sylphy.png"),
    Character("Eris Boreas Greyrat", "Mushoku Tensei", "Femenino", EPICO, "images/eris.png"),
    Character("Paul Greyrat", "Mushoku Tensei", "Masculino", EPICO, "images/paul.png"),
    Character("Zenith Greyrat", "Mushoku Tensei", "Femenino", RARO, "images/zenith.png"),
    Character("Ghislaine Dedoldia", "Mushoku Tensei", "Femenino", RARO, "images/ghislaine.png"),
    Character("Orsted", "Mushoku Tensei", "Masculino", RARO, "images/orsted.png"),
    Character("Ruijerd", "Mushoku Tensei", "Masculino", POCO_COMUN, "images/ruijerd.png"),
    Character("Hitogami", "Mushoku Tensei", "Masculino", POCO_COMUN, "images/hitogami.png"),
    Character("Lilia Greyrat", "Mushoku Tensei", "Femenino", COMUN, "images/lilia.png"),

    # ==================== BERSERK (15) ====================
    Character("Guts", "Berserk", "Masculino", LEGENDARIO, "images/guts.png"),
    Character("Griffith", "Berserk", "Masculino", EPICO, "images/griffith.png"),
    Character("Casca", "Berserk", "Femenino", EPICO, "images/casca.png"),
    Character("Skull Knight", "Berserk", "Masculino", EPICO, "images/skullknight.png"),
    Character("Judeau", "Berserk", "Masculino", EPICO, "images/judeau.png"),
    Character("Puck", "Berserk", "Masculino", RARO, "images/puck.png"),
    Character("Rickert", "Berserk", "Masculino", RARO, "images/rickert.png"),
    Character("Farnese", "Berserk", "Femenino", RARO, "images/farnese.png"),
    Character("Serpico", "Berserk", "Masculino", POCO_COMUN, "images/serpico.png"),
    Character("Isidro", "Berserk", "Masculino", POCO_COMUN, "images/isidro.png"),
    Character("Nosferatu Zodd", "Berserk", "Masculino", POCO_COMUN, "images/zodd.png"),
    Character("Corkus", "Berserk", "Masculino", COMUN, "images/corkus.png"),
    Character("Azan", "Berserk", "Masculino", COMUN, "images/azan.png"),

    # ==================== DR. STONE (15) ====================
    Character("Senku Ishigami", "Dr. Stone", "Masculino", LEGENDARIO, "images/senku.png"),
    Character("Taiju Oki", "Dr. Stone", "Masculino", EPICO, "images/taiju.png"),
    Character("Yuzuriha Ogawa", "Dr. Stone", "Femenino", EPICO, "images/yuzuriha.png"),
    Character("Tsukasa Shishio", "Dr. Stone", "Masculino", EPICO, "images/tsukasa.png"),
    Character("Gen Asagiri", "Dr. Stone", "Masculino", EPICO, "images/gen.png"),
    Character("Kinro", "Dr. Stone", "Masculino", RARO, "images/kinro.png"),
    Character("Ginro", "Dr. Stone", "Masculino", RARO, "images/ginro.png"),
    Character("Kohaku", "Dr. Stone", "Femenino", RARO, "images/kohaku.png"),
    Character("Suika", "Dr. Stone", "Femenino", POCO_COMUN, "images/suika.png"),
    Character("Chrome", "Dr. Stone", "Masculino", POCO_COMUN, "images/chrome.png"),
    Character("Ryusui Nanami", "Dr. Stone", "Masculino", COMUN, "images/ryusui.png"),

    # ==================== FIRE FORCE (15) ====================
    Character("Shinra Kusakabe", "Fire Force", "Masculino", LEGENDARIO, "images/shinra.png"),
    Character("Arthur Boyle", "Fire Force", "Masculino", EPICO, "images/arthur.png"),
    Character("Akitaru Obi", "Fire Force", "Masculino", EPICO, "images/obi.png"),
    Character("Takehisa Hinawa", "Fire Force", "Masculino", EPICO, "images/hinawa.png"),
    Character("Maki Oze", "Fire Force", "Femenino", EPICO, "images/maki_ff.png"),
    Character("Tamaki Kotatsu", "Fire Force", "Femenino", RARO, "images/tamaki.png"),
    Character("Viktor Licht", "Fire Force", "Masculino", RARO, "images/viktor.png"),
    Character("Princess Hibana", "Fire Force", "Femenino", POCO_COMUN, "images/hibana.png"),
    Character("Sho Kusakabe", "Fire Force", "Masculino", POCO_COMUN, "images/sho_ff.png"),
    Character("Konro Sagamiya", "Fire Force", "Masculino", COMUN, "images/konro.png"),

    # ==================== KAKEGURUI (15) ====================
    Character("Yumeko Jabami", "Kakegurui", "Femenino", LEGENDARIO, "images/yumeko.png"),
    Character("Ryota Suzui", "Kakegurui", "Masculino", EPICO, "images/ryota.png"),
    Character("Mary Saotome", "Kakegurui", "Femenino", EPICO, "images/mary.png"),
    Character("Kirari Momobami", "Kakegurui", "Femenino", EPICO, "images/kirari.png"),
    Character("Midari Ikishima", "Kakegurui", "Femenino", RARO, "images/midari.png"),
    Character("Ririka Momobami", "Kakegurui", "Femenino", RARO, "images/ririka.png"),
    Character("Kaede Manyuda", "Kakegurui", "Masculino", RARO, "images/kaede.png"),
    Character("Itsuki Sumeragi", "Kakegurui", "Femenino", POCO_COMUN, "images/itsuki.png"),
    Character("Sayaka Igarashi", "Kakegurui", "Femenino", POCO_COMUN, "images/sayaka.png"),
    Character("Runa Yomozuki", "Kakegurui", "Femenino", POCO_COMUN, "images/runa.png"),

    # ==================== MASHLE (15) ====================
    Character("Mash Burnedead", "Mashle", "Masculino", LEGENDARIO, "images/mash.png"),
    Character("Finn Ames", "Mashle", "Masculino", EPICO, "images/finn.png"),
    Character("Lance Crown", "Mashle", "Masculino", EPICO, "images/lance.png"),
    Character("Abel Walker", "Mashle", "Masculino", EPICO, "images/abel.png"),
    Character("Lemon Irvine", "Mashle", "Femenino", RARO, "images/lemon.png"),
    Character("Dot Barrett", "Mashle", "Masculino", RARO, "images/dot.png"),
    Character("Raj Grant", "Mashle", "Masculino", RARO, "images/raj.png"),

    # ==================== APOTHECARY DIARIES (15) ====================
    Character("Maomao", "Apothecary Diaries", "Femenino", LEGENDARIO, "images/maomao.png"),
    Character("Jinshi", "Apothecary Diaries", "Masculino", EPICO, "images/jinshi.png"),
    Character("Gaoshun", "Apothecary Diaries", "Masculino", EPICO, "images/gaoshun.png"),

    # ==================== SLIME DATTA KEN (15) ====================
    Character("Rimuru Tempest", "Tensei Slime", "Masculino", LEGENDARIO, "images/rimuru.png"),
    Character("Benimaru", "Tensei Slime", "Masculino", EPICO, "images/benimaru.png"),
    Character("Shion", "Tensei Slime", "Femenino", EPICO, "images/shion.png"),
    Character("Shuna", "Tensei Slime", "Femenino", EPICO, "images/shuna.png"),
    Character("Souei", "Tensei Slime", "Masculino", EPICO, "images/souei.png"),
    Character("Hakuro", "Tensei Slime", "Masculino", RARO, "images/hakuro.png"),
    Character("Gobta", "Tensei Slime", "Masculino", RARO, "images/gobta.png"),
    Character("Ranga", "Tensei Slime", "Masculino", RARO, "images/ranga.png"),
    Character("Diablo", "Tensei Slime", "Masculino", POCO_COMUN, "images/diablo.png"),
    Character("Milim Nava", "Tensei Slime", "Femenino", POCO_COMUN, "images/milim.png"),
    Character("Veldora", "Tensei Slime", "Masculino", POCO_COMUN, "images/veldora.png"),
]
